# Generated by Django 3.1.2 on 2020-10-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_callback_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callback',
            old_name='form',
            new_name='cat_form',
        ),
    ]
