# Generated by Django 3.1.2 on 2020-10-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_buyfeed_downfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cat_form', models.CharField(max_length=128)),
            ],
        ),
    ]
